version: '2'
services:
    jirapster-app:
        image: jirapster
        external_links:
            - jirapster-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jirapster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jirapster-mysql:
        extends:
            file: mysql.yml
            service: jirapster-mysql
